---
mqtt:
  host: test.mosquitto.org
  port: 1883

hashtags:
  - arduino
  - dbpedialite
  - debian
  - eventmachine
  - ipv6
  - marquette
  - mochad
  - mosquitto
  - multicast
  - mqtt
  - nanode
  - oggcamp
  - raspberry_pi
  - rsmb
  - ubuntu
  - uksnow

users:
  - andrewdlindsay
  - andypiper
  - andysc
  - chemicaloliver
  - ciemon
  - davejlocke
  - knolleary
  - lauracowen
  - monsonite
  - mqttorg
  - njh
  - pachube
  - pyrhho
  - ralight
  - red_ferries
  - redjets
